[user]
useConfigOnly = true
signingKey = F7A40E4EE148AC801B1509FD5163F032DF111539

[author]
name = shc/w
email = sh@c

[committer]
name = Shengdi 'shc' Chen (w)
email = me@shengdichen.xyz

# vim: filetype=gitconfig
