[user]
useConfigOnly = true
signingKey = F7A40E4EE148AC801B1509FD5163F032DF111539

[author]
name = shc/qiminfo
email = shengdi.chen@qiminfo.ch

[committer]
name = Shengdi 'shc' Chen (qiminfo)
email = shengdi.chen@qiminfo.ch

# vim: filetype=gitconfig
