[user]
useConfigOnly = true
signingKey = F7A40E4EE148AC801B1509FD5163F032DF111539

[author]
name = shc/skyguide
email = shengdi.chen@skyguide.ch

[committer]
name = Shengdi 'shc' Chen (skyguide)
email = shengdi.chen@skyguide.ch

# vim: filetype=gitconfig
